### ISSUE TITLE
You cannot download and upload the same reports twice

### ISSUE THREAD

**Issue by mhdirkse** [wearefrank/ladybug-frontend#121]
Steps to reproduce:
* Start the backend, do not stop it during this test.
* Using the example webapp, create two reports.
* Open the front-end.
* Open the two reports and copy them.
* Go to the test tab. It should have two reports.
* Select both reports and press "Download binary". A file should be downloaded.
* Press upload and select the file you just downloaded.
* There are four reports now.
* Delete all reports from the test tab.
* Go to the debug tab.
* Close all reports.
* Using the example webapp, clear the debug storage.
* Refresh the front-end. There should be no reports in the table and no open reports in the tree.
* Using the example webapp, use the same links to create two reports.
* Open the reports in the front-end, copy them.
* Go to the test tab.
* In the downloads directory, remove the reports you downloaded in the previous steps.
* Download and upload the reports in the test tab.
* Error: There are still two reports, not four. In the Tomcat window of the server, you see a response with response code 400. It says: `No ttr files found in zip`.

**Comment by MarkvdVorst** [comment]
I cannot reproduce the bug when I follow your steps. Is this still an issue? It might just be win11 not refreshing your download folder and grabbing a non-existing file.

**Comment by jacodg** [comment]
@mhdirkse can you retest?

**Comment by mhdirkse** [comment]
I retested and I cannot reproduce neither. I think there is no reason to test downloading and uploading in general right now. It should be done, but not as part of deciding about this issue.
