### ISSUE TITLE
Make Ladybug customizations configurable for Frank developers

### ISSUE THREAD

**Issue by mhdirkse** [wearefrank/ladybug-frontend#164]
Ladybug can be customized by manipulating Spring beans. This is not comfortable for Frank developers. We want a solution that allows Frank developers to do these customizations.

A possible approach is to introduce a YAML-based programming language.

Jaco emailed an overview of all Ladybug customizations that our customers did. The subject of that email is: "RE: Ladybug customisations".

**Comment by MatthijsSmets** [comment]
I don't see how we could easily implement this on the frontend, as it means having to restart the backend if I understand correctly?

**Comment by mhdirkse** [comment]
I agree this is a backend issue.
