### ISSUE TITLE
Add dynamic selection of storage when running a report 

### ISSUE THREAD

**Issue by celmoussaoui** [wearefrank/ladybug-frontend#197]
User should be able to select on which storage the user wants to rerun the report.

**Comment by mhdirkse** [comment]
Dit staat er een beetje ongelukkig, Je treft een rapport aan in een storage en je kan besluiten het te rerunnen. Het is niet zo dat een rapport ergens buiten een storage zou bestaat en dat je zou kunnen bepalen "welke storage het rerunnen moet doen". Alsof een storage een soort runner zou zijn.

Wat is hier de bedoeling, @jacodg ?

**Comment by jacodg** [comment]
Weet ik ook niet. Deze kunnen we wel sluiten. Je doet een rerun in een bepaalde tab / view en dan lijkt me dat de storage die daarbij is geconfigureerd gebruikt moet worden.
