### ISSUE TITLE
Create option in test tab for which storage to use in running report

### ISSUE THREAD

**Issue by celmoussaoui** [wearefrank/ladybug-frontend#220]
// TODO: Add param debugStorageName and use testTool.getStorage(debugStorageName) (frontend can use the storage
// name of the default view or add a dropdown to the Test tab for the user to select the debug view from which
// the storage should be used

**Comment by mhdirkse** [comment]
Ik vind dit niet zo duidelijk, @jacodg. Wat moet er met dit issue gebeuren?

**Comment by jacodg** [comment]
Is mij ook niet zo duidelijk, ik sluit hem
