### ISSUE TITLE
Implement gray box view

### ISSUE THREAD

**Issue by celmoussaoui** [wearefrank/ladybug-frontend#225]

**Comment by celmoussaoui** [comment]
This entails only showing the startpoints, senders and endpoints.

Also add black box which only shows startpoints and endpoints

**Comment by mhdirkse** [comment]
Hoort dit issue wel hier? Worden de views niet in het Frank!Framework gedefinieerd, het FF! subproject ladybug? En is het niet al gedaan? Ik kan dit op het moment niet zo snel checken omdat Ladybug niet werkt in Frank2Example.

**Comment by mhdirkse** [comment]
@MatthijsSmets je appte net: "Black box view wel, gray nog niet".

**Comment by MatthijsSmets** [comment]
No longer an issue, closing this. If any issues still occur with this, create an issue on [the backend](https://github.com/wearefrank/ladybug)
