### ISSUE TITLE
Make sure tomcat also throws errors

### ISSUE THREAD

**Issue by celmoussaoui** [wearefrank/ladybug-frontend#235]
Use log.error in exceptions so that errors are also correctly displayed in the tomcat.

Also think about situations where someone malicious wants to try different urls

In fact redo the error handling now that we have more knowledge on them. We should be able to catch all errors

**Comment by mhdirkse** [comment]
@MatthijsSmets is dit nog van toepassing. Dit ziet er uit als een idee voor refactoring, maar daar zijn jij, Mark en Rick al mee bezig.

**Comment by MatthijsSmets** [comment]
This should be moved to @wearefrank/ladybug, the refactoring we're doing is in the frontend, not the backend. Backend refactoring is something to be done at a much later time.

**Comment by Matthbo** [comment]
> Use log.error in exceptions so that errors are also correctly displayed in the tomcat.

This does not make any sense for the frontend, client-side errors can't and won't be thrown in tomcat but inside the browser.
Better logging in the backend is always welcome of course, but I think it's better to close this issue as it's irrelevant for the frontend
