### ISSUE TITLE
When a pipe uses parameters, their values do not stand out

### ISSUE THREAD

**Issue by mhdirkse** [wearefrank/ladybug-frontend#238]
When a pipe has `<Param>` elements, the values of these parameters are difficult to see.

In the old Ladybug GUI, you see the parameter value immediately.

![image](https://user-images.githubusercontent.com/6784732/190132857-41fd7c39-09a0-4211-bef0-50aa45ef6be8.png)

In the new GUI, your eyes are drawn to the table with properties about the parameter. You need to look carefully to see the parameter value above the table.

![image](https://user-images.githubusercontent.com/6784732/190133521-848af43d-347f-4a88-908b-bd8a6fd82652.png)

**Comment by celmoussaoui** [comment]
Are these not two different checkpoints and therefore have a different message?

**Comment by mhdirkse** [comment]
Het gaat hier om de rechterkant van de screenshot. Met de boomstructuur links is niets aan de hand.

Aan de rechterkant zie je bovenaan de waarde van de parameter staan, maar je oog valt eerder op wat eronder staat, properties "Name", "Thread name", "Source class name" enzovoorts.

**Comment by MatthijsSmets** [comment]
This looks a lot different now with all the changes made to ladybug the last few months, I don't think this is still relevant. Can you confirm @mhdirkse ?

**Comment by mhdirkse** [comment]
I will close this and make a reminder to test again.
