### ISSUE TITLE
When editing a report the tree doesn't have buttons like expand all

### ISSUE THREAD

**Issue by jacodg** [wearefrank/ladybug-frontend#306]
![image](https://github.com/ibissource/ladybug-frontend/assets/2970084/d27f5ebe-6f86-4686-aca7-14a508738362)

Missing buttons like:

![image](https://github.com/ibissource/ladybug-frontend/assets/2970084/8426ea58-dac9-4f14-9157-902052d79312)

**Comment by mhdirkse** [comment]
Wordt userstory 1031a en 1031b.
