### ISSUE TITLE
The same report can be opened multiple times

### ISSUE THREAD

**Issue by mhdirkse** [wearefrank/ladybug-frontend#37]
This issue was found using the ladybug-frontend project combined with the ibis-ladybug-test-webapp example project. With "ng serve" in the ladybug-frontend project, the Angular GUI is served. It calls the backend implemented in projects ibis-ladybug and ibis-ladybug-test-webapp. The ibis-ladybug-test-webapp also offers a .jsp page that can be used to create reports. With this setup, the issue can be reproduced as follows:
* Create two reports using the .jsp page.
* Open Ladybug.
* Click a report in the table. It is opened.
* Click "Open All". Both reports are opened. The report that was opened in the previous step appears twice now in the view of open reports.

**Comment by celmoussaoui** [comment]
I think we have established that this is a feature instead of a bug, so can it be closed?

**Comment by MatthijsSmets** [comment]
This is not a feature and will be refactored, clicking the same report twice should focus it in the tree.
