### ISSUE TITLE
Make use of delete all in report api

### ISSUE THREAD

**Issue by jacodg** [wearefrank/ladybug-frontend#370]
See https://github.com/wearefrank/ladybug/pull/218

Can we use this function when using the delete button without having a report selected?

The delete all needs to have an extra "are you sure?" action.

**Comment by mhdirkse** [comment]
Dit lijkt me error prone. Stel dat de GUI en de server niet gesynchroniseerd zijn. De gebruiker wil alle rapporten weggooien die hij ziet. Onze frontend code stuurt de API request om alle rapporten weg te gooien van de storage op de server. Maar er verdwijnen andere rapporten dan de gebruiker denkt. Dit probleem geldt zowel voor de debug tab als voor de test tab. Eens, @MatthijsSmets ?

**Comment by jacodg** [comment]
Waarom zouden er andere rapporten verdwijnen dan de gebruiker denkt? Als hij alle reports van een view/storage weg wil gooien en de "weet je het zeker?" bevestigd heeft waarom zouden er dan reports van een andere storage weggegooid worden?

**Comment by MatthijsSmets** [comment]
I agree with @jacodg, adding an `Are you sure?` popup should be enough
