### ISSUE TITLE
Error not visible to user

### ISSUE THREAD

**Issue by jacodg** [wearefrank/ladybug-frontend#379]
Currently DatabaseStorage doesn't work with PostgreSQL, old GUI shows:

![image](https://github.com/wearefrank/ladybug-frontend/assets/2970084/484775fb-cb56-4c2d-b618-77e082f99969)

But in new GUI everything looks fine:

![image](https://github.com/wearefrank/ladybug-frontend/assets/2970084/9cd61376-0295-452a-8761-2f4519addf05)

**Comment by mhdirkse** [comment]
Treedt dit alleen in PoesgreSQL op? Hoe komt het dat er een groot object wordt opgeslagen in de LADYBUG tabel? Hoe groot moet het object zijn om deze fout te triggeren?

**Comment by jacodg** [comment]
Tot nu toe alleen bij PostgreSQL gezien. We slaan de reports op in een BLOB. Ook bij kleine reports van zo'n 2500 bytes treedt dit op. Ik heb lokaal nu een transactie manager erbij geconfigureerd dat lost het probleem op.

**Comment by mhdirkse** [comment]
Hoort niet op dit bord. Gekopiëerd naar https://github.com/wearefrank/ladybug-ff-cypress-test/issues/9.

**Comment by jacodg** [comment]
Waarom hoort dit issue hier niet? Het probleem moet toch verholpen worden in de front-end? Los daarvan moet er ook een test van komen, als je daar liever een issue voor hebt op een ander bord prima.

**Comment by mhdirkse** [comment]
The issue is that a low-level error is not properly shown in the ladybug bèta user interface. Do you have a suggestion on how to produce a relevant low-level error in the ladybug-test-webapp?

**Comment by mhdirkse** [comment]
@jacodg I can do this research myself. I shall try to reproduce the issue by updating ladybug-test-webapp. If I can do so, I can then write a Cypress test in ladybug-frontend.

**Comment by jacodg** [comment]
I think you can create a Storage class in the test webapp that extends nl.nn.testtool.storage.memory.Storage and have getWarningsAndErrors() return an error message. And configure this new class as an extra storage/view in springTestToolTestWebapp.xml

**Comment by mhdirkse** [comment]
I will write an API endpoint in the Ladybug project that calls getWarningsAndErrors(). When we have that, I will inform Matthijs.

**Comment by mhdirkse** [comment]
Matthijs heeft mij gevraagd om de Cypress test te maken als hij dit feature geïmplementeerd heeft. Dat zal ik doen.

**Comment by MatthijsSmets** [comment]
On seconds thought, this is not something that should be shown in the ladybug-frontend. I think it would fit more if this was something that is checked when the backend is started.

**Comment by jacodg** [comment]
This error will only occur when a message is being processed and not at start-up. The user should be informed of such runtime errors

**Comment by mhdirkse** [comment]
Wordt story 5020.
