### ISSUE TITLE
When you select one or more reports in the beta front-end and press delete, a Java StackTrace appears

### ISSUE THREAD

**Issue by mhdirkse** [wearefrank/ladybug-frontend#381]
Expected behavior is that a toast window is shown. The window should say that deleting multiple reports is not supported for this storage.

![image](https://github.com/wearefrank/ladybug/assets/6784732/69751069-2d3b-47fa-af06-88dabcb2e96e)

This happened in version 2.3-20240316.003130.

**Comment by jacodg** [comment]
Why is is deleting multiple reports not supported? Which storage are you using?

In the test webapp I can select multiple reports and delete them

**Comment by mhdirkse** [comment]
Ik kan het niet meer reproduceren. @MatthijsSmets hebben jij en Mark iets veranderd aan het verwijderen van rapporten?
