### ISSUE TITLE
CTRL-F in Ladybug

### ISSUE THREAD

**Issue by Geert-Jan-DH** [wearefrank/ladybug-frontend#382]
It would be nice to be able to use CTRL-F key-combination on "Ladybug (beta)"

**Comment by jacodg** [comment]
Is this still needed?

**Comment by philipsens** [comment]
![image](https://github.com/wearefrank/ladybug-frontend/assets/12416423/08497cc0-78f0-433d-9ca9-ced6d771df95)
It is possible to search through the output, but you first need to click on it. If yea mean something else, please clarify.

**Comment by philipsens** [comment]
Reopen this issue if this is not the solution you were looking for. If so, please clarify the problem and what solution you are looking for.

**Comment by Geert-Jan-DH** [comment]
I'm happy with the current solution.
