### ISSUE TITLE
There is an API call to remove all reports at once

### ISSUE THREAD

**Issue by mhdirkse** [wearefrank/ladybug-frontend#384]
The Ladybug backend supports an API call now to remove all reports at once. All reports of the debug tab at once and another endpoint to remove all reports of the test tab at once. That backend call is useful for the Cypress tests. Should we also use it in the ladybug-frontend? I see the following options:

* We make a separate button in the GUI te remove all reports; or
* There is a checkbox to select all reports already. If the user clicks the existing delete button, then the frontend checks whether all reports are selected. If so, the delete all API call is used. Otherwise, each report is deleted separately. Drawback: if the frontend and backend are out of sink, too many reports may be deleted; or
* Because of these considerations, ladybug-frontend should always delete each report separately. In that case the delete all API call should stay in the backend to support the Cypress tests.

**Comment by mhdirkse** [comment]
Shall we close this, @MatthijsSmets?

**Comment by MatthijsSmets** [comment]
This will be implemented using a delete all button preferably in the settings windows.
