### ISSUE TITLE
Refactor updatePath method in test.component.ts

### ISSUE THREAD

**Issue by MatthijsSmets** [wearefrank/ladybug-frontend#393]
In the test component, update path and the form that triggers it should be refactored to use Angular's built in form support, instead of using query selector and value={{}}. This is not the only place where this happens all places where a querySelector is used can be replaced with the angular way.

**Comment by MarkvdVorst** [comment]
The queryselector already gets fixed with the PR for issue #409

**Comment by MarkvdVorst** [comment]
The use of value={{}} example gets fixed in the PR for issue #396
