### ISSUE TITLE
Pressing the rerun button in open new tab shows the wrong error

### ISSUE THREAD

**Issue by MarkvdVorst** [wearefrank/ladybug-frontend#415]
![afbeelding](https://github.com/wearefrank/ladybug-frontend/assets/34445874/58fc7857-7baa-4406-a2e5-3abd31e9dc21)

User should not see an error like this and error handling should be applied instead to offer a better error message.

**Comment by mhdirkse** [comment]
Welke tab was dit, was het niet de debug tab en ook niet de test tab? Heb je iets gedaan om een fout uit te lokken zodat je de foutafhandeling kon testen?

**Comment by MatthijsSmets** [comment]
This error is not reproducable, is this still a problem? @MarkvdVorst

**Comment by MarkvdVorst** [comment]
This issue was solved when we refactored some of the rerun functionalities
