### ISSUE TITLE
Show report description in Test tab

### ISSUE THREAD

**Issue by jacodg** [wearefrank/ladybug-frontend#424]
A user can give a report a description by editing a report. The old GUI will show this description in the Test tab:

![image](https://github.com/wearefrank/ladybug-frontend/assets/2970084/57b3fb56-8a60-4377-8151-a99268fdedf8)

**Comment by mhdirkse** [comment]
Dit is user story nummer 2040.

**Comment by mhdirkse** [comment]
En story 3005. Issue 2040 zegt dat je een description kan invullen. Story 3005 zegt dat hij zichtbaar moet zijn in de test tab.

**Comment by mhdirkse** [comment]
Ik keek verkeerd. Staat niet onder de naam maar in een aparte kolom.
