### ISSUE TITLE
Consider adding a RootLevelReport type

### ISSUE THREAD

**Issue by philipsens** [wearefrank/ladybug-frontend#463]
https://github.com/wearefrank/ladybug-frontend/pull/425#discussion_r1662354121

There are assertions on the XML property of a report to see if it is a report or a top level report. I want to suggest making a partial type or something, to make it more clear that these are two different things.

**Comment by mhdirkse** [comment]
Ik begrijp dit issue niet. Kunnen rapporten dan genest zijn in de debug tree? En wat voor assertions betreft het hier?

**Comment by philipsens** [comment]
Ja zoiets. Het als je de gelinkte PR bekijkt is de originele conversatie terug te vinden.
