### ISSUE TITLE
Indentation of nodes in debug tree is not what I expected

### ISSUE THREAD

**Issue by mhdirkse** [wearefrank/ladybug-frontend#467]
Indentation of nodes in debug tree is not what I expected. I tested this by running a test adapter that calls another adapter through a JavaListener.

![image](https://github.com/wearefrank/ladybug-frontend/assets/6784732/ac124ddd-b679-4378-8789-9bc4d0312adf)

![image](https://github.com/wearefrank/ladybug-frontend/assets/6784732/6c7095c1-b7d2-41a0-bae4-64088a452d7c)

This applies to all levels of the tree. In the user stories it is written that the checkpoint that closes a group is considered as the last child (story 1020). That would mean that the last child has to appear one position more to the right. And also that it has to disappear when the node is collapsed. If you collapse a node now, you keep the start and the end checkpoint.

This issue can also be fixed by updating story 1020.

**Comment by jacodg** [comment]
I think Martijn has a valid point. Although I would maybe need to see it in a bigger picture. Looking on my local development environment I see the following:

![image](https://github.com/wearefrank/ladybug-frontend/assets/2970084/e33f13fa-d3e2-4f08-a71e-a2127714485a)

Here it seems to be the way Martijn suggests it should be. This is with version 0.0.54.

Dotted lines like in the old Ladybug could possibly make it a lot clearer:

![image](https://github.com/wearefrank/ladybug-frontend/assets/2970084/0d332467-e644-48b0-9021-bc7e4dd3a45f)
