### ISSUE TITLE
Metadata table is not styled nicely

### ISSUE THREAD

**Issue by mhdirkse** [wearefrank/ladybug-frontend#468]
When you select a thread node in the debug tree while the metadata is shown, it looks as follows:

![image](https://github.com/wearefrank/ladybug-frontend/assets/6784732/bfdaa161-89d0-484f-946c-f818e924e4fa)

The picture you see here is the metadata. When you hide the metadata, you do not see anything here anymore which is fine.

**Comment by nielsm5** [comment]
I would argue that it's not style nicely, regardless of the debug-tree-page you're on.
