### ISSUE TITLE
Scrolling through the value of a node in the debug tree does not work well

### ISSUE THREAD

**Issue by mhdirkse** [wearefrank/ladybug-frontend#470]
I found this issue by visiting the following node in the debug tree:

![image](https://github.com/wearefrank/ladybug-frontend/assets/6784732/133daa11-3af0-4da4-89a7-845c7f85dae2)

I could only scroll through this value using the mouse wheel. I could not use the scroll bar shown to the right.

**Comment by MatthijsSmets** [comment]
What do you mean with this value?

**Comment by mhdirkse** [comment]
I mean the panel to the right of the debug tree. It is filled with a large piece of XML in the figure because the root node of a report is selected.

**Comment by MatthijsSmets** [comment]
You actually can scroll, but because of a backend error the "xml" is very long, you can see the scroll bar has a very small clickable part:

![Image](https://github.com/user-attachments/assets/5b504d4d-efca-422f-9ca0-e212e6153c70)

Also, you have a minimap just like VS-code than can be used to scroll as well.

**Comment by mhdirkse** [comment]
Ik denk dat ik naar de verkeerde scroll bar keek. Aan je pijl zie ik dat er twee naast elkaar zijn en dat jij de meest linkse aanwijst. Ik zal dat checken.

**Comment by mhdirkse** [comment]
Er zijn er drie naast elkaar, zie ik nu. De meest linkse scroll bar valt mij niet op. Je ziet het knopje waar je hem kan pakken pas als je erover hoovert. Is het mogelijk om het knopje altijd zichtbaar te laten zijn?

**Comment by MatthijsSmets** [comment]
If you mean the minimap scroll bar, then no, not easily, this is from a third party package.

**Comment by mhdirkse** [comment]
We have https://github.com/wearefrank/ladybug-frontend/issues/559 now.
