### ISSUE TITLE
Toggling Show multiple files in debug file-tree setting has some weird behavior

### ISSUE THREAD

**Issue by MatthijsSmets** [wearefrank/ladybug-frontend#478]
I enable the `Show multiple files in debug file-tree` setting and open a bunch of files in the tree.\
![image](https://github.com/wearefrank/ladybug-frontend/assets/93487259/dd726f60-633e-4fa1-a47d-9b7d6cefbc17)

After that I close them all
![image](https://github.com/wearefrank/ladybug-frontend/assets/93487259/cd9e0cee-4494-48fc-ae80-1a10c21f46eb)

Then if I disable the `Show multiple files in debug file-tree` setting again, it opens the last closed report.
![image](https://github.com/wearefrank/ladybug-frontend/assets/93487259/24777b57-1cc3-48aa-92a1-003688e9479e)

**Comment by mhdirkse** [comment]
Het is in ladybug-frontend versie 0.1.0-20240710.153412 al beter, maar nog niet goed. Je kan hetzelfde rapport nog steeds meerdere keren openen.
