### ISSUE TITLE
In the compare tab, selecting checkpoints is not synchronized

### ISSUE THREAD

**Issue by mhdirkse** [wearefrank/ladybug-frontend#487]
![image](https://github.com/wearefrank/ladybug-frontend/assets/6784732/2cbf460d-f641-45b3-98ef-c86d9a9f1cfa)

In the compare tab, you can select checkpoints. I would expect that if you change some checkpoint to the left, then the corresponding checkpoint is selected to the right automatically. This does not happen. You just compare checkpoints that are unrelated unless you select the correct checkpoint at both sides.

**Comment by mhdirkse** [comment]
Wordt story 3108. Ik dacht dat ik hier al over geschreven had maar zonder deze nieuwe story is het nog niet scherp.

**Comment by MatthijsSmets** [comment]
This is because the `Compare method` is set to `None` in the dropdown menu, if you set it to `Path` or `Checkpoint` number it will try to sync both threes
