### ISSUE TITLE
Rerunning a report fails where I would expect it to succeed - do we need default ignores?

### ISSUE THREAD

**Issue by mhdirkse** [wearefrank/ladybug-frontend#489]
![image](https://github.com/wearefrank/ladybug-frontend/assets/6784732/edeb50c9-8260-4a0f-a1c6-4e79f00a6ba1)

I reran a report that succeeded and that did not access external systems. It fails because some uninteresting session keys are different:

![image](https://github.com/wearefrank/ladybug-frontend/assets/6784732/a23caba9-3c65-40a9-8ba4-944599237454)

![image](https://github.com/wearefrank/ladybug-frontend/assets/6784732/0edc05f4-6d2c-42e0-b424-28cbc23424eb)

**Comment by MatthijsSmets** [comment]
This should be an error for the backend.

**Comment by mhdirkse** [comment]
Wordt story 2012.

**Comment by mhdirkse** [comment]
Hoort hier inderdaad niet.
