### ISSUE TITLE
Automatic refresh when report is updated

### ISSUE THREAD

**Issue by ricklue** [wearefrank/ladybug-frontend#508]
When you edit a report, the new values are not updated in the report table and the debug-tree after the edit. It happens only if you click on the refresh button.

**Comment by mhdirkse** [comment]
Wordt user story **2050** wat betreft de test tab. Ik weet nog niet of het editen van rapporten toegestaan moet zijn in de Debug tab. Daarom heb ik dit punt ook genoemd in een ongenummerd bullet point onder story **1240**.
