### ISSUE TITLE
Refactor edit-display component stub strategy dropdown

### ISSUE THREAD

**Issue by MatthijsSmets** [wearefrank/ladybug-frontend#518]
Stub strategy dropdown should be refactored to use ngModel, like @Matthbo suggested

              Wouldn't this be better with a ngModel?

_Originally posted by @Matthbo in https://github.com/wearefrank/ladybug-frontend/pull/517#discussion_r1682977931_

**Comment by ricklue** [comment]
Stub strategy is now also not in the request body, because otherwise it is not possible to update the message from a checkpoint.
See issue in Ladybug backend (https://github.com/wearefrank/ladybug/issues/267#issue-2408583547)
