### ISSUE TITLE
Sorting the table by column is reset when refresh is triggered

### ISSUE THREAD

**Issue by MatthijsSmets** [wearefrank/ladybug-frontend#561]
If the table is sorted by name and a refresh is triggered, sorting gets reset.

**Comment by ricklue** [comment]
![Image](https://github.com/user-attachments/assets/6a44136c-ee72-44d0-87ef-561fb2a5ceda)

I believe this is the reason...

**Comment by MarkvdVorst** [comment]
I just checked the bug and it seems like they fixed it at some point since I put this here. This whole thing was also discussed with @MatthijsSmets in the past when I put this there.

I'll create a PR for a fix.
