### ISSUE TITLE
In the test tab, cannot expand and collapse the folder structure to the left

### ISSUE THREAD

**Issue by mhdirkse** [wearefrank/ladybug-frontend#563]
I had reports in the test tab. Then I typed a name in the edit box for the folder name and pressed the copy button. I expected that the highlighted field below could be expanded:

![image](https://github.com/user-attachments/assets/5f4681b2-8af5-4e50-a8a8-924847b2a353)

However, I could not expand the field. It is thus not possible to navigate the folder structure of reports by mouse clicks.

Something about managing reports in a folder structure did work. I could type the name of my folder to select it. Then it also expanded to the left as shown.

![image](https://github.com/user-attachments/assets/0adf22f5-7c8b-42ec-9b8b-34b8e5753da8)

**Comment by MatthijsSmets** [comment]
Can you clarify the actual issue here?

In your first picture your reports are in the root folder, which is called `Reports`, you can't expand the root folder if it does not have any sub folders like is the case with your first example.

**Comment by mhdirkse** [comment]
Om dit issue te kunnen testen moest ik een rapport in de Test tab naar een folder verplaatsen, zoals in onderstaand screenshot:

![image](https://github.com/user-attachments/assets/bdbd5e31-7470-4652-bcf8-6418da787a18)

Waarschijnlijk was mijn fout dat ik het rapport vergat te selecteren voordat ik op copy drukte. Ik had maar één rapport en verwachtte dat het systeem hem zou kopiëren zonder dat hij geselecteerd was. Toen ik hem eerst selecteerde voordat ik op copy drukte, toen verscheen de nieuwe folder aan de linkerkant. Ik kon de root folder ook met de muis open en dicht klikken. Kanttekening is dat ik daarvoor het > of v icoontje precies moest raken. Dubbelklikken op een andere plaats op de regel werkte niet. Ik ga Jaco vragen of dat een issue is. Dit issue is wat mij betreft opgelost.

**Comment by mhdirkse** [comment]
Er is ook nog een toast dat er geen rapport geselecteerd was. Jammer voor mij dat ik die toast niet goed zie, maar ik denk dat andere mensen daar geen probleem mee zullen hebben. Nog een reden om dit issue te sluiten.
