### ISSUE TITLE
Display window does not close when checkpoint is selected when closing the reports on the left.

### ISSUE THREAD

**Issue by MarkvdVorst** [wearefrank/ladybug-frontend#566]
![afbeelding](https://github.com/user-attachments/assets/4cc19012-82d2-4fe0-a725-aa47f276ae8e)

Steps to reproduce:
1. Open one or more reports in the Debug tab.
2. Select a startpoint or endpoint.
3. Press the X in the left tree view to close the reports.

An error will appear when you close the report while the checkpoint is selected that the selectedNode is undefined.
Furthermore, when this bug happens the user cannot close the window on the right anymore and will keep getting the same error as shown in the screenshot.

**Comment by MatthijsSmets** [comment]
I can't reproduce this error, could this just be a one off?
