### ISSUE TITLE
In compare tab, the tree structure is not shown correctly

### ISSUE THREAD

**Issue by mhdirkse** [wearefrank/ladybug-frontend#583]
When you are comparing reports in the compare tab, the tree structure is not shown correctly. The old GUI has:

![image](https://github.com/user-attachments/assets/593906ab-66a4-4628-94c9-4b74d6ab19ae)

All nodes have the correct indentation and can be collapsed / expanded.

In the new GUI it looks like this:

![image](https://github.com/user-attachments/assets/c5622c11-398c-48d7-b576-073d0be4695b)

There are three levels of indentation here - the indentation of the shown nodes is correct. But you cannot expand further.

**Comment by mhdirkse** [comment]
To the right, the session keys do not have the right icon.

**Comment by MarkvdVorst** [comment]
As said in teams, this is the old compare tab from production. Current version in frontend has already replaced these icons and implemented a new tree with the ng-simple-file-tree that @MatthijsSmets made. Is this still an issue considering this?
