### ISSUE TITLE
I cannot see and edit the stub strategy of a report

### ISSUE THREAD

**Issue by jacodg** [wearefrank/ladybug-frontend#590]
In Debug tab:

![image](https://github.com/user-attachments/assets/ac93ab42-44a3-438a-95e0-faa9f76d7a9f)

![image](https://github.com/user-attachments/assets/9b7482e6-f98d-426e-a451-27d5cb7f38fd)

And when opening new tab:

![image](https://github.com/user-attachments/assets/a83eef6b-d1e6-43b1-8bfa-e6b73502d35e)

![image](https://github.com/user-attachments/assets/c496b00e-0c02-4a83-9412-05887f3b3a8a)

**Comment by MatthijsSmets** [comment]
Issue already existed: #305
