### ISSUE TITLE
Expand and collapse in the tree needs precise clicking to prevent selecting the node instead of expand or collapse

### ISSUE THREAD

**Issue by jacodg** [wearefrank/ladybug-frontend#591]
When in the screenshot below you click on the red marked area it will select the checkpoint instead of collapsing it. A second click will then collapse it but as a user you would like to collapse it without selecting the checkpoint.

![image](https://github.com/user-attachments/assets/629d4f2e-da8a-4d61-859d-d5ea93cf0828)

Also when you click on the following area once it will select the node and a second click on that area will collapse the node:

![image](https://github.com/user-attachments/assets/c4b09257-5228-4138-93a8-707b31d11bb6)

I think it would be better to give this area only the function of selecting a node and the collapse/expand icon only the function of collapse and expand

**Comment by MatthijsSmets** [comment]
It's also an option to allow the node to expand if the user double clicks, is that also acceptable or do you want it like you described?
