### ISSUE TITLE
False toaster messages "Opened report in progress with index [1]"

### ISSUE THREAD

**Issue by jacodg** [wearefrank/ladybug-frontend#631]
With the test webapp click a number of times on "[Waiting for message to be captured](http://localhost/index.jsp?createReport=Waiting%20for%20message%20to%20be%20captured)" and then use Refresh button:

![image](https://github.com/user-attachments/assets/33ac3e9f-53b3-4faf-90c0-8809f919c3c6)

**Comment by MatthijsSmets** [comment]
This has been fixed in #626 are you on the latest version of master?

**Comment by mhdirkse** [comment]
I tested this and I do not see the reported behavior. I do not trust that I tested it correctly because there may be a misunderstanding about the issue. Therefore I assign it to @jacodg.
