### ISSUE TITLE
Cypress test wanted that expanding and collapsing only happens when > or v is hit exactly

### ISSUE THREAD

**Issue by mhdirkse** [wearefrank/ladybug-frontend#653]
This issue originates from a conversation with Jaco. I asked him whether expanding and collapsing node should be possible by clicking a row in the debug tree. Or if expanding / collapsing should only happen when the > or v sign is hit exactly. The latter is what Jaco wants. And Ladybug conforms to that. So this issue is not about a bug. I suggest we make a test in the Cypress tests to document that we want this behavior, and to have a regression test that this behavior does not change.

**Comment by mhdirkse** [comment]
@MatthijsSmets, I assign this to you because you, Mark and Rick took charge of the Cypress tests of ladybug-frontend in the past. I would like to focus on writing user stories and on testing in combination with the Frank!Framework.

**Comment by MatthijsSmets** [comment]
I don't think this needs a cypress test, as this is something the ng-simple-file-tree package does by default. Writing tests to test a package does not make sense in my opinion.

**Comment by mhdirkse** [comment]
Ok. In theory our product can be refactored in the future to use another library. To guard against that a test could make sense. But this would only be reasonable if our product would be mature already. We have more pressing considerations, so accepted.
