### ISSUE TITLE
Deleting reports and changing subfolders in the test tab

### ISSUE THREAD

**Issue by mhdirkse** [wearefrank/ladybug-frontend#654]
The following actions in the test tab cause a surprise:
* In the root folder, select multiple reports from different folders.
* Change to a subfolder from which some records were selected.
* You only see the reports that are in the subfolder, works as expected.
* Press the delete button.
* See the error: the confirmation dialog shows all reports initially selected, also the ones that were not visible anymore when delete was pressed.

Expected behavior: reports that get out of scope should not be deleted, as confirmed by @jacodg. Question: does this also mean that reports should be deselected when they get out of sight?

**Comment by jacodg** [comment]
When not visible I don't see where they can be (de)selected. In memory waiting to be displayed in the future?

**Comment by mhdirkse** [comment]
Suppose you have reports in different folder. When you are in the root you can see them all. Suppose you select reports from different folder. When you select a subfolder, you do not see all selected reports. Should the frontend automatically de-select the reports that no longer shown?

This would have two implications. First if you would select the root folder again, less reports would be selected than you originally selected. Only the reports you selected earlier that were also in the subfolder would be selected at this point. Second, this approach guarantees that the reports being deleted are always the selected reports.

Or do we do it the other way. We can also remember what reports were selected when we change subfolder. Then you have the same reports selected again when you select a subfolder and then the root folder again. But if you press delete, you are not deleting all selected reports, only the subset of selected reports that is in the currently selected subfolder.

**Comment by jacodg** [comment]
I don't thinks we should remember selected folders after a different folder has been clicked. When a folder is clicked I think is is nice when all the reports which are direct children of this folder are selected by default and all report that are shown because they are in a subfolder of the selected folder are unselected by default. This is also how the old GUI is doing it.

**Comment by MatthijsSmets** [comment]
A fix for the test tab folders in is review right now, please check if this issue still persists after merging with master or check this issue on branch: `fix/test-tab-folders`
- [ ] #650

**Comment by mhdirkse** [comment]
When I change folders, all reports are selected by default. OK.
When I select all reports of the root folder, select a subfolder and press delete, only one report is eligible for deletion.
But when I confirm the delete, all my reports are gone! Not OK. Refreshing the reports and refreshing the browser does not help.

**Comment by MatthijsSmets** [comment]
This should be fixed now, please check.

**Comment by mhdirkse** [comment]
Works now.
