### ISSUE TITLE
When I have opened a report, I need to enter edit mode to see the description

### ISSUE THREAD

**Issue by mhdirkse** [wearefrank/ladybug-frontend#721]
![image](https://github.com/user-attachments/assets/0509291c-cebf-4d38-94a2-b1e4d55dfe0f)

This is how my report looks like - it was opened from the Test tab. I do not see a description. To see the description, I have to enter edit mode. But when I do not want to edit, I do not want to enter edit mode. Expected behavior is that the description is visible without the need to enter edit mode.

**Comment by MatthijsSmets** [comment]
If your report has a description it will show it in the XML:
![Image](https://github.com/user-attachments/assets/e49f3a8e-b915-4a02-a3ed-399cd263634b)
So you don't have to switch to edit mode to see it.

**Comment by mhdirkse** [comment]
Ah, I did not see that. The description is an important piece of information. It is used to browse through reports to find the report you are looking for. I suggest you show it in a way that stands out more. Now it is buried in data that is less important.

@jacodg, I assign this issue to you to make a decision.

**Comment by jacodg** [comment]
In Debug reports don't have a description. In Test a user can add a description which will be visible in the overview. Hence no need to show it when opening a report
