### ISSUE TITLE
Rerun success message doesn't contain all information

### ISSUE THREAD

**Issue by jacodg** [wearefrank/ladybug-frontend#741]
On rerun of a report there is a summary of the rerun available which is shown in the old GUI but not available in the new GUI:

![image](https://github.com/user-attachments/assets/dc9b020c-44f4-43d7-9699-9c011012866d)

![image](https://github.com/user-attachments/assets/9b9bcf74-1636-4e5a-95fd-eb126f558bba)

**Comment by mhdirkse** [comment]
Moet er ook een link bij om in de compare tab te komen? Of moet de gebruiker zelf het nieuwe rapport en het originele rapport selecteren en compare doen?

**Comment by jacodg** [comment]
Dat laatste. Al zou het eerste natuurlijk best een mooie hulp zijn voor een gebruiker. Dus we kunnen er een nice to have issue voor inschieten :)

**Comment by jacodg** [comment]
I should have looked here:

![image](https://github.com/user-attachments/assets/c407846f-7739-4cb5-b83c-4e6c1734752b)
