### ISSUE TITLE
Some top buttons act on the selected sub folder, some on all reports in the Test tab

### ISSUE THREAD

**Issue by mhdirkse** [wearefrank/ladybug-frontend#753]
When I am in a sub folder and press the delete all button, then all the reports of the Test tab are gone, also the ones that were not in the sub folder.

When I am in a sub folder and press rerun, then only the selected reports are rerun. This implies that reports outside the selected folder are not rerun.

It is confusing that buttons at the same row have a different scope.

**Comment by MatthijsSmets** [comment]
Would it make more sense to have the general buttons, buttons for selected reports and buttons for only one report separated by a divider like so:
![Image](https://github.com/user-attachments/assets/9f2717f9-3d1a-4b93-ad59-da6d6b7af1bd)

I could also add a title to each section like so:
![Image](https://github.com/user-attachments/assets/4d1fe35e-4e9a-47ac-a408-70329ca2500a)

**Comment by mhdirkse** [comment]
Ik ben voor de layout van het onderste rijtje. @jacodg?

**Comment by jacodg** [comment]
Ja, ik ook
